# Generated by Django 5.0.7 on 2024-11-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterprofile',
            name='contract_number',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='contract_number',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
